spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    username: studym
    password: studym
    url: jdbc:mysql://localhost:5000/study_marathon


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      springframework:
        security:
          web: TRACE
    com:
      github:
        studym:
          studymarathon: debug


  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              lient-id: 127921108602-i8hep7gvpmeip8cuv46v0tcfep6f392d.apps.googleusercontent.com
              client-secret: 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
              scope: email

