spring:
  profiles:
    active: local

  servlet:
    multipart:
      enabled: true
      location: c:\\upload
      max-request-size: 300MB
      max-file-size: 50MB


  datasource:
    username: ${MYSQL_USER_ID}
    password: ${MYSQL_USER_PW}
    url: jdbc:mysql://localhost:5000/study_marathon

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  logging:
    file:
      path: c/Log
      max-size: 500MB
      max-history: 10
    level:
      org:
        springframework:
          security:
            web: TRACE
      com:
        github:
          studym:
            studymarathon: debug


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email



com:
  github:
    studym:
      studymarathon:
        path: C:\\upload