spring:
  profiles:
    active: local



  datasource:
    username: studym
    password: studym
    url: jdbc:mysql://localhost:5000/study_marathon


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  logging:
    level:
      org:
        springframework:
          security:
            web: TRACE
      com:
        github:
          studym:
            studymarathon: debug


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 24738469717-2lfdge2b9b6ile9rnesvvee46hq52ktp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email





